### ISSUE TITLE
Inconsistent messaging around $0 accepted

### ISSUE THREAD

**Issue by davedawson** [nickbytes/taken-from-nra#14]
[Elizabeth Warren's page](https://fervent-pasteur-a1e5b2.netlify.com/elizabeth-warren/) shows the correct language, but for some reason not all reps do. [Dan Sullivan's page](https://fervent-pasteur-a1e5b2.netlify.com/dan-sullivan/) says "has accepted $0"

**Comment by nickbytes** [comment]
https://github.com/nickbytes/taken-from-nra/blob/master/src/templates/each-template.js#L77

Changing this line to `>` will probably fix this.

Elizabeth Warren's number is negative, so she gets `false` message, while Dan Sullivan's was exactly $0, so he got the `true` message.

**Comment by nickbytes** [comment]
This is resolved now, updated ternary.
