### ISSUE TITLE
Sticky sidebar homepage

### ISSUE THREAD

**Issue by davedawson** [nickbytes/taken-from-nra#15]
The left side should stay at the top (on desktop). Figure out a way to do that. Maybe waypoints?

![image](https://user-images.githubusercontent.com/958923/42459401-8d2cdf80-8369-11e8-9b05-de654876a688.png)

**Comment by davedawson** [comment]
@nickbytes Is there anything special I need to do to add a component to the project? Looking at [React Waypoints](https://github.com/brigade/react-waypoint) to solve this. Ok to just `yarn add` this thing?

**Comment by davedawson** [comment]
Yep, that's the plan. But, the left sidebar is too tall for most screens, so we need it to scroll until it hits the bottom of the content, then remain sticky. I was thinking of using waypoints to do that.

**Comment by nickbytes** [comment]
Ah, I get it now. Sounds cool, let me know if I can help at all with it.

**Comment by nickbytes** [comment]
#34 PR here you can work off of, I think it's firing at the correct time + adding a class. Let me know how else I can help here.

**Comment by nickbytes** [comment]
This is done!!!! @davedawson

**Comment by davedawson** [comment]
🎉
