### ISSUE TITLE
CSS blending mode isn't working on staging

### ISSUE THREAD

**Issue by davedawson** [nickbytes/taken-from-nra#18]
**Local:** 
![image](https://user-images.githubusercontent.com/958923/42459563-e8f1b502-8369-11e8-9fba-62dece917e4c.png)

**Staging:**
![image](https://user-images.githubusercontent.com/958923/42459577-f218292c-8369-11e8-9f4e-3a4f1c745e30.png)

**Comment by nickbytes** [comment]
Did you see it flash the correct way on load? Weird

**Comment by nickbytes** [comment]
Hmmm this works sometimes. This is probably my issue with routing differently (capitalized vs not), you should let me handle this.

**Comment by davedawson** [comment]
This is a weird one. Sometimes I can get it displaying correctly on staging, but if I refresh the blend effect goes away.

**Comment by nickbytes** [comment]
This is resolved now, sent you some comments in slack about this, but basically: styled-components don't like it when you try to use classNames with them.
