### ISSUE TITLE
Share links

### ISSUE THREAD

**Issue by davedawson** [nickbytes/taken-from-nra#19]
Hook up FB & Twitter share links. Dependent on #21.

**Comment by davedawson** [comment]
@nickbytes I added the FB share link. But I hit a wall with Twitter. Would you be able to create the Twitter share string, similar to how you set up the imgix string? Ideally the default Twitter share text would read: 
`[individual name]` has received `[amount]` from the @NRA. Learn more and take action at moneyoverpeople.org
_Or_ if 0 or less dollars received: 
`[individual name]` has not received any money from the @NRA. Learn more and take action at moneyoverpeople.org

Crazy idea for v2: Can we pull in the individual's twitter handle to include them in these share tweets?

**Comment by nickbytes** [comment]
@davedawson Nice work!

> But I hit a wall with Twitter. Would you be able to create the Twitter share string, similar to how you set up the imgix string?

Yep, I can jump on this tonight/tomorrow.

> Crazy idea for v2: Can we pull in the individual's twitter handle to include them in these share tweets?

This would be really cool, I'm sure we could find a data set that has these to sync up with our data.

**Comment by nickbytes** [comment]
@davedawson I think you just need to edit what you want the text to say within a tweet now.

I created a function so we can change the text depending on whether they have taken donations or not. We use the function [here](https://github.com/nickbytes/taken-from-nra/blob/master/src/templates/each-template.js#L197).

[Here](https://github.com/nickbytes/taken-from-nra/blob/master/src/templates/each-template.js#L51) is where you would edit the message.

Each message gets the reps URL (moneyoverpeople.org/john-doe) after the text.

**Comment by davedawson** [comment]
Amazing. Thanks for setting that up. Just added the new text in. 👍
