### ISSUE TITLE
Share graphics

### ISSUE THREAD

**Issue by davedawson** [nickbytes/taken-from-nra#21]
I know you're already working on this, but creating an issue for you anyways, @nickbytes.

**Comment by nickbytes** [comment]
@davedawson here is where we are currently

<img src="https://assets.imgix.net/~text?w=320&txtsize=26&txtpad=20&txtfont64=SGVsdmV0aWNhIE5ldWUgTGlnaHQ&txtclr=fff&txt=John%20McCain%20has%20accepted%20$7,755,701%20from%20the%20NRA.&fm=png&dpr=2&bg=ff1127" />

Where are we trying to go?

Here are some typeface options. What do you think of these?

**Comment by davedawson** [comment]
So cool! Is this in a branch somewhere that I can explore and mess around with the layout?

**Comment by nickbytes** [comment]
💥 https://github.com/nickbytes/taken-from-nra/pull/26

**Comment by nickbytes** [comment]
@davedawson Let me mess with that sandbox image. Looks goods.

> Also, were you able to figure out how these images work, or how much they cost? I want to make sure we're paying for them if we need to be. It seems crazy that we're able to just generate an image like that without having an account or anything, right?

Yea agreed. Maybe we need to shoot them an email and ask what the limits are for free usage. Otherwise, I'm pretty sure I could run a task that would just download all of them once.

**Comment by nickbytes** [comment]
@davedawson are you able to get the watermark to work?

**Comment by davedawson** [comment]
I'm happy to pay, just let me know if I need to create an account and set up billing. But, $3/1000 requests can add up very quickly, so if that's how that works, then yeah downloading them all at once might be a better set up. 

> are you able to get the watermark to work?

I wasn't able to. But, I added a png logo graphic to our repo, and then added the url to the imgix call to pull it in relative to root, but obviously won't work until everything up on staging.
