### ISSUE TITLE
Remove placeholder rep image

### ISSUE THREAD

**Issue by davedawson** [nickbytes/taken-from-nra#22]
Seen here: https://fervent-pasteur-a1e5b2.netlify.com/jaime-herrera-beutler/
![image](https://user-images.githubusercontent.com/958923/42459864-94ca5c26-836a-11e8-8355-05f27b123fda.png)

**Comment by davedawson** [comment]
I removed the placeholder image from `headshots.js`, but the page is now pulling in an empty image here. How can we make that a conditional that only displays if there's a headshot image available?

**Comment by nickbytes** [comment]
Should be resolved here: https://github.com/nickbytes/taken-from-nra/pull/30
